ALTER TABLE USERS         ENABLE ROW LEVEL SECURITY;
ALTER TABLE EMPLOYEE      ENABLE ROW LEVEL SECURITY;
ALTER TABLE CATEGORY      ENABLE ROW LEVEL SECURITY;
ALTER TABLE BOARD_GAME    ENABLE ROW LEVEL SECURITY;
ALTER TABLE GAME_CATEGORY ENABLE ROW LEVEL SECURITY;
ALTER TABLE GAME_COPY     ENABLE ROW LEVEL SECURITY;
ALTER TABLE BOOKING       ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read/write (prototype only)" ON USERS
    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public read/write (prototype only)" ON EMPLOYEE
    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public read/write (prototype only)" ON CATEGORY
    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public read/write (prototype only)" ON BOARD_GAME
    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public read/write (prototype only)" ON GAME_CATEGORY
    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public read/write (prototype only)" ON GAME_COPY
    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public read/write (prototype only)" ON BOOKING
    FOR ALL USING (true) WITH CHECK (true);
