import { reactive, ref } from 'vue'
import type { SupabaseClient } from '@supabase/supabase-js'
import { FALLBACK_PRESENTATION, gamePresentation } from '~/composables/gamePresentation'

// Matches the status CHECK constraint on public.booking in supabase/schema.sql
export type BookingStatus = 'Reserved' | 'In_Use' | 'Overdue' | 'Returned' | 'Cancelled'

// Matches the condition_status CHECK constraint on public.game_copy
export type CopyCondition = 'Good' | 'Fair' | 'Damaged' | 'Lost'

export const CONDITION_LABELS: Record<CopyCondition, string> = {
  Good: 'ดี',
  Fair: 'พอใช้',
  Damaged: 'ชำรุด',
  Lost: 'สูญหาย'
}

/** Upper bound for one "add boxes" action, to catch a mistyped extra zero. */
export const MAX_COPIES_PER_ADD = 20

export interface Copy {
  id: string
  label: string
  number: number
  condition: CopyCondition
}

/**
 * Damaged or lost boxes stay on record — bookings reference them and the FK is
 * ON DELETE RESTRICT — but they are not offered to customers.
 */
export function isUsableCopy(copy: Copy) {
  return copy.condition === 'Good' || copy.condition === 'Fair'
}

export interface Category {
  id: string
  name: string
}

export interface Game {
  id: string
  name: string
  description: string
  icon: string
  image?: string
  category: string
  categoryId: string | null
  minP: number
  maxP: number
  playtime: number
  /** Every box on record, including retired ones; customers should use usableCopies(). */
  copies: Copy[]
  howToPlay: string[]
}

/** The editable fields of public.board_game plus its (single) category link. */
export interface GameInput {
  name: string
  description: string
  minP: number
  maxP: number
  playtime: number
  categoryId: string | null
}

/** Mirrors public.users. user_id is generated by the system — nobody types it. */
export interface User {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
}

export interface Booking {
  id: string
  gameId: string
  copyId: string
  userId: string
  start: Date
  end: Date
  status: BookingStatus
  actualReturn: Date | null
}

export interface BookingInput {
  firstName: string
  lastName: string
  email: string
  phone: string
  gameId: string
  copyId: string
  start: Date
  end: Date
}

type DbError = { code?: string, message?: string } | null

function normalizeEmail(email: string) {
  return email.trim().toLowerCase()
}

function normalizePhone(phone: string) {
  return phone.replace(/[^0-9]/g, '')
}

/**
 * public.booking stores TIMESTAMP (no time zone), so send local wall-clock text.
 * Sending a Date directly would serialise to UTC and shift every booking by the
 * device's offset (-7h in Thailand).
 */
function toDbTimestamp(d: Date) {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`
}

/** '2026-09-08T14:00:00' has no offset, so JS parses it as local time — the inverse of the above. */
function fromDbTimestamp(value: string) {
  return new Date(value)
}

/** Turns a Postgres constraint violation into the message a booker should see. */
function messageForDbError(err: DbError): string {
  if (!err) return 'บันทึกข้อมูลไม่สำเร็จ'
  const detail = `${err.code ?? ''} ${err.message ?? ''}`
  if (err.code === '23P01' || detail.includes('exc_booking_no_overlap')) {
    return 'ช่วงเวลานี้ถูกจองไปแล้ว กรุณาเลือกเวลาอื่น (BR-03)'
  }
  if (detail.includes('chk_booking_duration')) {
    return 'ระยะเวลาการจองต้องอยู่ระหว่าง 30 นาที ถึง 4 ชั่วโมง (BR-02)'
  }
  if (detail.includes('chk_booking_return_time')) {
    return 'เวลาคืนต้องไม่ก่อนเวลาเริ่มใช้งาน'
  }
  if (err.code === '23505' && detail.includes('email')) {
    return 'อีเมลนี้ถูกใช้กับชื่ออื่นแล้ว กรุณาตรวจสอบอีกครั้ง'
  }
  return `บันทึกข้อมูลไม่สำเร็จ: ${err.message ?? 'ไม่ทราบสาเหตุ'}`
}

const NO_CATALOG_PERMISSION = 'ไม่มีสิทธิ์แก้ไขข้อมูลเกม กรุณาเข้าสู่ระบบเจ้าหน้าที่ใหม่'
const COPY_HAS_HISTORY = 'กล่องนี้มีประวัติการจองแล้ว ลบไม่ได้ ให้เปลี่ยนสภาพเป็น "ชำรุด" หรือ "สูญหาย" แทน เพื่อเลิกให้บริการ'

/** Same idea as messageForDbError, for employees editing games and stock. */
function messageForCatalogError(err: DbError): string {
  if (!err) return 'บันทึกข้อมูลไม่สำเร็จ'
  const detail = `${err.code ?? ''} ${err.message ?? ''}`
  if (err.code === '42501') return NO_CATALOG_PERMISSION
  if (err.code === '23503' || detail.includes('fk_booking_copy')) return COPY_HAS_HISTORY
  if (detail.includes('chk_board_game_player_range')) return 'จำนวนผู้เล่นสูงสุดต้องไม่น้อยกว่าขั้นต่ำ'
  if (err.code === '23505') return 'รหัสเกมหรือรหัสกล่องซ้ำกับที่มีอยู่ กรุณาลองใหม่อีกครั้ง'
  if (err.code === '22001') return 'ข้อมูลยาวเกินกว่าที่ระบบรองรับ'
  return `บันทึกข้อมูลไม่สำเร็จ: ${err.message ?? 'ไม่ทราบสาเหตุ'}`
}

let store: ReturnType<typeof createStore> | null = null

function createStore(supabase: SupabaseClient) {
  const simNow = ref(new Date())
  const isTimeOverridden = ref(false)

  const games = reactive<Game[]>([])
  const categories = reactive<Category[]>([])
  const users = reactive<User[]>([])
  const bookings = reactive<Booking[]>([])

  const loading = ref(true)
  const loadError = ref<string | null>(null)

  // ---------- loading ----------

  async function loadAll() {
    loading.value = true
    loadError.value = null
    try {
      const [gameRes, copyRes, linkRes, categoryRes, userRes, bookingRes] = await Promise.all([
        supabase.from('board_game').select('*').order('game_name'),
        supabase.from('game_copy').select('*').order('copy_code'),
        supabase.from('game_category').select('game_id, category:category_id (category_id, category_name)'),
        supabase.from('category').select('*').order('category_name'),
        supabase.from('users').select('*'),
        supabase.from('booking').select('*').order('start_time')
      ])

      const firstError = gameRes.error || copyRes.error || linkRes.error || categoryRes.error || userRes.error || bookingRes.error
      if (firstError) throw firstError

      categories.splice(0, categories.length, ...(categoryRes.data ?? []).map(row => ({
        id: row.category_id,
        name: row.category_name
      })))

      const categoryByGame = new Map<string, Category>()
      for (const row of linkRes.data ?? []) {
        const cat = row.category as { category_id?: string, category_name?: string } | null
        if (cat?.category_id && cat.category_name && !categoryByGame.has(row.game_id)) {
          categoryByGame.set(row.game_id, { id: cat.category_id, name: cat.category_name })
        }
      }

      const copiesByGame = new Map<string, Copy[]>()
      const copyToGame = new Map<string, string>()
      for (const row of copyRes.data ?? []) {
        const list = copiesByGame.get(row.game_id) ?? []
        list.push({
          id: row.copy_id,
          label: row.copy_code,
          number: row.copy_number,
          condition: row.condition_status as CopyCondition
        })
        copiesByGame.set(row.game_id, list)
        copyToGame.set(row.copy_id, row.game_id)
      }

      games.splice(0, games.length, ...(gameRes.data ?? []).map(row => {
        const look = gamePresentation[row.game_id] ?? FALLBACK_PRESENTATION
        const category = categoryByGame.get(row.game_id)
        return {
          id: row.game_id,
          name: row.game_name,
          description: row.description ?? '',
          icon: look.icon,
          image: look.image,
          category: category?.name ?? 'อื่นๆ',
          categoryId: category?.id ?? null,
          minP: row.min_players,
          maxP: row.max_players,
          playtime: row.play_time_mins,
          copies: copiesByGame.get(row.game_id) ?? [],
          howToPlay: look.howToPlay
        }
      }))

      users.splice(0, users.length, ...(userRes.data ?? []).map(row => ({
        id: row.user_id,
        firstName: row.first_name,
        lastName: row.last_name,
        email: row.email,
        phone: row.phone ?? ''
      })))

      bookings.splice(0, bookings.length, ...(bookingRes.data ?? []).map(row => ({
        id: row.booking_id,
        gameId: copyToGame.get(row.copy_id) ?? '',
        copyId: row.copy_id,
        userId: row.user_id,
        start: fromDbTimestamp(row.start_time),
        end: fromDbTimestamp(row.end_time),
        status: row.status as BookingStatus,
        actualReturn: row.actual_return_time ? fromDbTimestamp(row.actual_return_time) : null
      })))

      await recomputeOverdue()
    } catch (e: unknown) {
      const err = e as { message?: string }
      loadError.value = err.message ?? 'โหลดข้อมูลจากฐานข้อมูลไม่สำเร็จ'
    } finally {
      loading.value = false
    }
  }

  // ---------- id generation (schema uses VARCHAR primary keys, not sequences) ----------

  /**
   * Next `${prefix}NNN` id. Ids are compared as numbers, not text: sorting text puts
   * 'GM-WEREWOLF' above 'GM-007' and 'BK-999' above 'BK-1000', which would hand out
   * an id that is already taken. Ids whose tail isn't a number are ignored.
   */
  async function nextId(table: string, column: string, prefix: string, pad: number) {
    const { data, error } = await supabase.from(table).select(column).like(column, `${prefix}%`)
    if (error) throw error

    let max = 0
    for (const row of (data ?? []) as unknown as Record<string, string>[]) {
      const tail = String(row[column] ?? '').slice(prefix.length)
      if (/^\d+$/.test(tail)) max = Math.max(max, Number(tail))
    }
    return prefix + String(max + 1).padStart(pad, '0')
  }

  // ---------- reads over loaded state ----------

  function getUser(userId: string) {
    return users.find(u => u.id === userId)
  }

  function userLabel(userId: string) {
    const u = getUser(userId)
    return u ? `${u.firstName} ${u.lastName}` : '—'
  }

  function getGame(gameId: string) {
    return games.find(g => g.id === gameId)
  }

  function usableCopies(game: Game) {
    return game.copies.filter(isUsableCopy)
  }

  function copyStatus(copy: Copy): 'free' | 'busy' {
    const blocking = bookings.some(b => b.copyId === copy.id && (b.status === 'In_Use' || b.status === 'Overdue'))
    return blocking ? 'busy' : 'free'
  }

  function freeCopyCount(game: Game) {
    return usableCopies(game).filter(c => copyStatus(c) === 'free').length
  }

  function bookingsForCopy(copyId: string) {
    return bookings
      .filter(b => b.copyId === copyId && b.status !== 'Returned' && b.status !== 'Cancelled')
      .sort((a, b) => +a.start - +b.start)
  }

  /** Any booking at all, finished or not — what blocks deleting a box. */
  function copyHasHistory(copyId: string) {
    return bookings.some(b => b.copyId === copyId)
  }

  function activeBookingCount(copyId: string) {
    return bookings.filter(b => b.copyId === copyId && (b.status === 'Reserved' || b.status === 'In_Use' || b.status === 'Overdue')).length
  }

  function activeBookingsForUser(userId: string) {
    return bookings.filter(b => b.userId === userId && (b.status === 'Reserved' || b.status === 'In_Use'))
  }

  function hasOverdue(userId: string) {
    return bookings.some(b => b.userId === userId && b.status === 'Overdue')
  }

  function todayAt(h: number, m: number) {
    const d = new Date(simNow.value)
    d.setHours(h, m, 0, 0)
    return d
  }

  // ---------- validation done in the app (the DB covers BR-02/BR-03 itself) ----------

  function validateInput({ firstName, lastName, email, phone, start, end }: BookingInput): string | null {
    if (!firstName.trim() || !lastName.trim()) return 'กรุณากรอกชื่อและนามสกุล'
    if (!email.trim()) return 'กรุณากรอกอีเมล'
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) return 'รูปแบบอีเมลไม่ถูกต้อง'
    const digits = normalizePhone(phone)
    if (digits && (digits.length < 9 || digits.length > 10)) return 'เบอร์โทรต้องมี 9-10 หลัก'
    if (isNaN(+start) || isNaN(+end)) return 'กรุณาระบุช่วงเวลาให้ถูกต้อง'
    if (end <= start) return 'เวลาสิ้นสุดต้องอยู่หลังเวลาเริ่ม'
    const mins = (end.getTime() - start.getTime()) / 60000
    if (mins < 30) return 'ระยะเวลาการจองต้องอย่างน้อย 30 นาที (BR-02)'
    if (mins > 240) return 'ระยะเวลาการจองต้องไม่เกิน 4 ชั่วโมง (BR-02)'

    // BR-01/BR-04 are per person; an unseen email is a new user with no history.
    const existing = users.find(u => u.email === normalizeEmail(email))
    if (existing) {
      if (hasOverdue(existing.id)) return 'คุณมีรายการค้างสถานะ Overdue โปรดคืนเกมก่อนจองใหม่ (BR-04)'
      if (activeBookingsForUser(existing.id).length >= 2) return 'คุณมีรายการจองที่ใช้งาน/รอใช้งานอยู่แล้ว 2 รายการ (BR-01)'
    }
    return null
  }

  // ---------- booking writes ----------

  /**
   * Email is the identity: booking again with the same address reuses the users row.
   * `wasCreated` lets the caller undo the insert if the booking itself is rejected,
   * so a failed attempt doesn't leave an orphan user behind.
   */
  async function findOrCreateUser(input: BookingInput): Promise<{ id: string, wasCreated: boolean }> {
    const email = normalizeEmail(input.email)

    const { data: found, error: findError } = await supabase
      .from('users').select('user_id').eq('email', email).maybeSingle()
    if (findError) throw findError
    if (found) return { id: found.user_id, wasCreated: false }

    const { data: created, error: insertError } = await supabase
      .from('users')
      .insert({
        user_id: await nextId('users', 'user_id', 'U', 3),
        first_name: input.firstName.trim(),
        last_name: input.lastName.trim(),
        email,
        phone: normalizePhone(input.phone) || null
      })
      .select('user_id')
      .single()
    if (insertError) throw insertError

    return { id: created.user_id, wasCreated: true }
  }

  async function addBooking(input: BookingInput): Promise<{ error: string | null }> {
    const invalid = validateInput(input)
    if (invalid) return { error: invalid }

    try {
      const user = await findOrCreateUser(input)

      const { error } = await supabase.from('booking').insert({
        booking_id: await nextId('booking', 'booking_id', 'BK-', 3),
        start_time: toDbTimestamp(input.start),
        end_time: toDbTimestamp(input.end),
        status: 'Reserved',
        user_id: user.id,
        copy_id: input.copyId
      })

      if (error) {
        // Roll back the user we just created, so a rejected booking leaves no trace.
        if (user.wasCreated) await supabase.from('users').delete().eq('user_id', user.id)
        return { error: messageForDbError(error) }
      }

      await loadAll()
      return { error: null }
    } catch (e: unknown) {
      return { error: messageForDbError(e as DbError) }
    }
  }

  /**
   * RLS lets only a signed-in employee update bookings. A blocked update comes back
   * with no error and zero rows, so success is judged by the rows returned.
   */
  async function markInUse(id: string, employeeId: string) {
    const { data, error } = await supabase
      .from('booking')
      .update({ status: 'In_Use', checkout_by_id: employeeId })
      .eq('booking_id', id)
      .select('booking_id')
    if (error || !data?.length) return null
    const local = bookings.find(b => b.id === id)
    if (local) local.status = 'In_Use'
    return local
  }

  async function markReturned(id: string, employeeId: string) {
    const now = new Date()
    const { data, error } = await supabase
      .from('booking')
      .update({ status: 'Returned', actual_return_time: toDbTimestamp(now), return_by_id: employeeId })
      .eq('booking_id', id)
      .select('booking_id')
    if (error || !data?.length) return null
    const local = bookings.find(b => b.id === id)
    if (local) {
      local.status = 'Returned'
      local.actualReturn = now
    }
    return local
  }

  /**
   * The F-04 overdue scan: flip In_Use bookings whose end_time has passed.
   * Always updated on screen; only persisted when an employee is signed in,
   * since customers' sessions aren't allowed to write bookings.
   */
  async function recomputeOverdue() {
    const stale = bookings.filter(b => b.status === 'In_Use' && simNow.value > b.end)
    if (!stale.length) return
    stale.forEach(b => { b.status = 'Overdue' })
    await supabase.from('booking').update({ status: 'Overdue' }).in('booking_id', stale.map(b => b.id))
  }

  // ---------- catalog writes (employees only; enforced by RLS) ----------

  function validateGameInput(input: GameInput): string | null {
    const name = input.name.trim()
    if (!name) return 'กรุณากรอกชื่อเกม'
    if (name.length > 150) return 'ชื่อเกมยาวได้ไม่เกิน 150 ตัวอักษร'
    if (!Number.isInteger(input.minP) || input.minP < 1) return 'จำนวนผู้เล่นขั้นต่ำต้องเป็นจำนวนเต็มตั้งแต่ 1 ขึ้นไป'
    if (!Number.isInteger(input.maxP) || input.maxP < input.minP) return 'จำนวนผู้เล่นสูงสุดต้องไม่น้อยกว่าขั้นต่ำ'
    if (!Number.isInteger(input.playtime) || input.playtime < 1) return 'เวลาเล่นต้องเป็นจำนวนเต็มนาทีตั้งแต่ 1 ขึ้นไป'
    return null
  }

  function toGameRow(input: GameInput) {
    return {
      game_name: input.name.trim(),
      description: input.description.trim() || null,
      min_players: input.minP,
      max_players: input.maxP,
      play_time_mins: input.playtime
    }
  }

  /** The ERD allows many categories per game; this app edits exactly one (or none). */
  async function setGameCategory(gameId: string, categoryId: string | null) {
    const { error: deleteError } = await supabase.from('game_category').delete().eq('game_id', gameId)
    if (deleteError) throw deleteError
    if (!categoryId) return
    const { error } = await supabase.from('game_category').insert({ game_id: gameId, category_id: categoryId })
    if (error) throw error
  }

  /**
   * Box codes continue the game's existing pattern (WW-01, WW-02 → WW-03) and fall
   * back to the game id. copy_id is VARCHAR(20), so its prefix is trimmed to fit.
   */
  async function insertCopies(gameId: string, existing: Copy[], count: number): Promise<string | null> {
    const fromExisting = existing[0]?.label.replace(/-\d+$/, '')
    const prefix = (fromExisting || gameId.replace(/^GM-/, '')).toUpperCase()

    let n = existing.reduce((max, c) => Math.max(max, c.number), 0)
    const rows = Array.from({ length: count }, () => {
      n += 1
      const nn = String(n).padStart(2, '0')
      return {
        copy_id: `CP-${prefix.slice(0, 16 - nn.length)}-${nn}`,
        copy_code: `${prefix}-${nn}`,
        condition_status: 'Good',
        copy_number: n,
        game_id: gameId
      }
    })

    const { data, error } = await supabase.from('game_copy').insert(rows).select('copy_id')
    if (error) return messageForCatalogError(error)
    if ((data?.length ?? 0) !== count) return NO_CATALOG_PERMISSION
    return null
  }

  async function createGame(input: GameInput, copyCount: number): Promise<{ error: string | null, id: string | null }> {
    const invalid = validateGameInput(input)
    if (invalid) return { error: invalid, id: null }
    if (!Number.isInteger(copyCount) || copyCount < 0 || copyCount > MAX_COPIES_PER_ADD) {
      return { error: `จำนวนกล่องเริ่มต้นต้องอยู่ระหว่าง 0-${MAX_COPIES_PER_ADD}`, id: null }
    }

    try {
      const id = await nextId('board_game', 'game_id', 'GM-', 3)
      const { error } = await supabase.from('board_game').insert({ game_id: id, ...toGameRow(input) })
      if (error) return { error: messageForCatalogError(error), id: null }

      await setGameCategory(id, input.categoryId)
      const copyError = copyCount > 0 ? await insertCopies(id, [], copyCount) : null

      await loadAll()
      // The game exists even if its boxes failed, so the caller can still open it.
      return { error: copyError, id }
    } catch (e: unknown) {
      return { error: messageForCatalogError(e as DbError), id: null }
    }
  }

  async function updateGame(gameId: string, input: GameInput): Promise<{ error: string | null }> {
    const invalid = validateGameInput(input)
    if (invalid) return { error: invalid }

    try {
      const { data, error } = await supabase
        .from('board_game').update(toGameRow(input)).eq('game_id', gameId).select('game_id')
      if (error) return { error: messageForCatalogError(error) }
      if (!data?.length) return { error: NO_CATALOG_PERMISSION }

      await setGameCategory(gameId, input.categoryId)
      await loadAll()
      return { error: null }
    } catch (e: unknown) {
      return { error: messageForCatalogError(e as DbError) }
    }
  }

  async function addCopies(gameId: string, count: number): Promise<{ error: string | null }> {
    if (!Number.isInteger(count) || count < 1 || count > MAX_COPIES_PER_ADD) {
      return { error: `เพิ่มได้ครั้งละ 1-${MAX_COPIES_PER_ADD} กล่อง` }
    }
    const game = getGame(gameId)
    if (!game) return { error: 'ไม่พบเกมนี้' }

    const error = await insertCopies(gameId, game.copies, count)
    if (error) return { error }
    await loadAll()
    return { error: null }
  }

  async function setCopyCondition(copyId: string, condition: CopyCondition): Promise<{ error: string | null }> {
    const { data, error } = await supabase
      .from('game_copy').update({ condition_status: condition }).eq('copy_id', copyId).select('copy_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  async function deleteCopy(copyId: string): Promise<{ error: string | null }> {
    if (copyHasHistory(copyId)) return { error: COPY_HAS_HISTORY }

    const { data, error } = await supabase.from('game_copy').delete().eq('copy_id', copyId).select('copy_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  // ---------- clock ----------

  function syncToRealTime() {
    if (isTimeOverridden.value) return
    simNow.value = new Date()
    void recomputeOverdue()
  }

  function setSimNow(d: Date) {
    isTimeOverridden.value = true
    simNow.value = d
    void recomputeOverdue()
  }

  function resetToRealTime() {
    isTimeOverridden.value = false
    simNow.value = new Date()
    void recomputeOverdue()
  }

  void loadAll()

  return {
    games,
    categories,
    users,
    bookings,
    loading,
    loadError,
    loadAll,
    getUser,
    userLabel,
    simNow,
    isTimeOverridden,
    todayAt,
    copyStatus,
    getGame,
    usableCopies,
    freeCopyCount,
    bookingsForCopy,
    copyHasHistory,
    activeBookingCount,
    addBooking,
    markInUse,
    markReturned,
    createGame,
    updateGame,
    addCopies,
    setCopyCondition,
    deleteCopy,
    setSimNow,
    syncToRealTime,
    resetToRealTime,
    recomputeOverdue
  }
}

export function useBoardGameStore() {
  if (!store) store = createStore(useSupabaseClient())
  return store
}
