import { computed, reactive, ref } from 'vue'
import type { SupabaseClient } from '@supabase/supabase-js'

// Matches the status CHECK constraint on public.booking in supabase/schema.sql
export type BookingStatus = 'Reserved' | 'In_Use' | 'Overdue' | 'Returned' | 'Cancelled'

// Matches the condition_status CHECK constraint on public.game_copy
export type CopyCondition = 'Good' | 'Fair' | 'Damaged' | 'Lost'

export const CONDITION_LABELS: Record<CopyCondition, string> = {
  Good: 'ดี',
  Fair: 'พอใช้',
  Damaged: 'ชำรุด',
  Lost: 'สูญหาย'
}

/** Upper bound for one "add boxes" action, to catch a mistyped extra zero. */
export const MAX_COPIES_PER_ADD = 20

/** Shown when board_game.icon is empty. Also the column's default in schema.sql. */
export const DEFAULT_ICON = '🎲'

/** A Reserved booking is held this long past its start time before it counts as a no-show. */
export const NO_SHOW_GRACE_MINUTES = 10

/**
 * How many returned bookings are kept. Older ones are deleted hourly by
 * prune_returned_history() — see supabase/migrate_prune_history.sql. Stated here
 * only so the dashboard can tell staff the history is capped.
 */
export const RETURNED_HISTORY_LIMIT = 200

export interface Copy {
  id: string
  label: string
  number: number
  condition: CopyCondition
}

/**
 * Damaged or lost boxes stay on record — bookings reference them and the FK is
 * ON DELETE RESTRICT — but they are not offered to customers.
 */
export function isUsableCopy(copy: Copy) {
  return copy.condition === 'Good' || copy.condition === 'Fair'
}

export interface Category {
  id: string
  name: string
}

export interface Game {
  id: string
  name: string
  description: string
  icon: string
  image?: string
  /** Every category linked through game_category, in name order. May be empty. */
  categories: Category[]
  minP: number
  maxP: number
  playtime: number
  /** Every box on record, including retired ones; customers should use usableCopies(). */
  copies: Copy[]
  /** From public.how_to_play_step, in step_number order. */
  howToPlay: string[]
  /**
   * board_game.deleted_at is set. The game is gone from the catalog and the employee
   * game list, but stays loaded so past bookings still show its name.
   */
  archived: boolean
  /** When it was archived (board_game.deleted_at); null for games customers can see. */
  archivedAt: Date | null
}

/** The editable fields of public.board_game plus its category links and how-to-play steps. */
export interface GameInput {
  name: string
  description: string
  icon: string
  minP: number
  maxP: number
  playtime: number
  categoryIds: string[]
  howToPlay: string[]
}

/** Mirrors public.users. user_id is generated by the system — nobody types it. */
export interface User {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
}

export interface Booking {
  id: string
  gameId: string
  copyId: string
  userId: string
  start: Date
  end: Date
  status: BookingStatus
  actualReturn: Date | null
  /**
   * The booker's name and phone as they stood when this booking was made, copied in
   * by trg_snapshot_booker. public.users holds only their current details, so editing
   * a name would otherwise rewrite it across every past booking. Empty until
   * migrate_booker_snapshot.sql has run; callers fall back to the users row.
   */
  bookerName: string
  bookerPhone: string
}

export interface BookingInput {
  firstName: string
  lastName: string
  email: string
  phone: string
  gameId: string
  copyId: string
  start: Date
  end: Date
}

type DbError = { code?: string, message?: string } | null

/** Result of an employee status change: the updated booking, or why it was refused. */
export type BookingUpdate = { booking: Booking | null, error: string | null }

function normalizeEmail(email: string) {
  return email.trim().toLowerCase()
}

function normalizePhone(phone: string) {
  return phone.replace(/[^0-9]/g, '')
}

/**
 * public.booking stores TIMESTAMP (no time zone), so send local wall-clock text.
 * Sending a Date directly would serialise to UTC and shift every booking by the
 * device's offset (-7h in Thailand).
 */
function toDbTimestamp(d: Date) {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`
}

/** '2026-09-08T14:00:00' has no offset, so JS parses it as local time — the inverse of the above. */
function fromDbTimestamp(value: string) {
  return new Date(value)
}

/** Postgres/PostgREST codes for "that table doesn't exist". */
function isMissingTable(err: DbError) {
  return err?.code === 'PGRST205' || err?.code === '42P01'
}

/** Turns a Postgres constraint violation into the message a booker should see. */
function messageForDbError(err: DbError): string {
  if (!err) return 'บันทึกข้อมูลไม่สำเร็จ'
  const detail = `${err.code ?? ''} ${err.message ?? ''}`
  // trg_enforce_booking_rules raises BR-01/BR-04/BR-05 already worded for the booker.
  const ruleViolation = (err.message ?? '').match(/BR-\d+:\s*([^\n]+)/)
  if (ruleViolation) return ruleViolation[1]!
  if (err.code === '23P01' || detail.includes('exc_booking_no_overlap')) {
    return 'ช่วงเวลานี้ถูกจองไปแล้ว กรุณาเลือกเวลาอื่น (BR-03)'
  }
  if (detail.includes('chk_booking_duration')) {
    return 'ระยะเวลาการจองต้องอยู่ระหว่าง 30 นาที ถึง 4 ชั่วโมง (BR-02)'
  }
  if (detail.includes('chk_booking_return_time')) {
    return 'เวลาคืนต้องไม่ก่อนเวลาเริ่มใช้งาน'
  }
  if (err.code === '23505' && detail.includes('email')) {
    return 'อีเมลนี้ถูกใช้กับชื่ออื่นแล้ว กรุณาตรวจสอบอีกครั้ง'
  }
  // Usually a stale browser tab still running code from before an RLS change.
  if (err.code === '42501') {
    return 'หน้าเว็บนี้เป็นเวอร์ชันเก่า กรุณากด Ctrl+Shift+R เพื่อโหลดใหม่ แล้วลองจองอีกครั้ง'
  }
  // Never show a raw Postgres message to a customer; keep it in the console instead.
  console.error('[booking] unexpected database error', err)
  return `บันทึกข้อมูลไม่สำเร็จ กรุณาลองใหม่อีกครั้ง${err.code ? ` (รหัส ${err.code})` : ''}`
}

const NO_CATALOG_PERMISSION = 'ไม่มีสิทธิ์แก้ไขข้อมูลเกม กรุณาเข้าสู่ระบบเจ้าหน้าที่ใหม่'
const NO_BOOKING_PERMISSION = 'บันทึกไม่สำเร็จ — สิทธิ์เจ้าหน้าที่อาจหมดอายุ กรุณาเข้าสู่ระบบใหม่'
const COPY_HAS_HISTORY = 'กล่องนี้มีประวัติการจองแล้ว ลบไม่ได้ ให้เปลี่ยนสภาพเป็น "ชำรุด" หรือ "สูญหาย" แทน เพื่อเลิกให้บริการ'
const MIGRATION_NEEDED = 'ฐานข้อมูลยังไม่ได้อัปเดต กรุณารันไฟล์ migration ในโฟลเดอร์ supabase/ ให้ครบก่อน'

function gameHasActiveBookingsMessage(count: number) {
  return `ลบไม่ได้ เพราะยังมีการจองที่ยังไม่จบ ${count} รายการ (จองไว้ กำลังใช้ หรือเกินกำหนด) ลบได้เมื่อการจองเหล่านั้นคืนเกมครบแล้ว`
}

/** ON DELETE RESTRICT raises 23001; 23503 is the same refusal for NO ACTION foreign keys. */
function isReferenced(err: DbError) {
  return err?.code === '23001' || err?.code === '23503'
}

/** Same idea as messageForDbError, for employees editing games and stock. */
function messageForCatalogError(err: DbError, whenReferenced = COPY_HAS_HISTORY): string {
  if (!err) return 'บันทึกข้อมูลไม่สำเร็จ'
  const detail = `${err.code ?? ''} ${err.message ?? ''}`
  if (err.code === '42501') return NO_CATALOG_PERMISSION
  if (isReferenced(err)) return whenReferenced
  if (isMissingTable(err) || (err.code === 'PGRST204' && (detail.includes('icon') || detail.includes('deleted_at')))) {
    return MIGRATION_NEEDED
  }
  if (detail.includes('chk_board_game_player_range')) return 'จำนวนผู้เล่นสูงสุดต้องไม่น้อยกว่าขั้นต่ำ'
  if (err.code === '23505' && detail.includes('category_name')) return 'มีหมวดหมู่ชื่อนี้อยู่แล้ว'
  if (err.code === '23505' && detail.includes('pk_game_category')) return 'เกมนี้อยู่ในหมวดหมู่นี้แล้ว'
  if (err.code === '23505') return 'รหัสเกมหรือรหัสกล่องซ้ำกับที่มีอยู่ กรุณาลองใหม่อีกครั้ง'
  if (err.code === '22001') return 'ข้อมูลยาวเกินกว่าที่ระบบรองรับ'
  console.error('[catalog] unexpected database error', err)
  return `บันทึกข้อมูลไม่สำเร็จ กรุณาลองใหม่อีกครั้ง${err.code ? ` (รหัส ${err.code})` : ''}`
}

let store: ReturnType<typeof createStore> | null = null

function createStore(supabase: SupabaseClient) {
  const simNow = ref(new Date())

  const games = reactive<Game[]>([])
  const categories = reactive<Category[]>([])
  const users = reactive<User[]>([])
  const bookings = reactive<Booking[]>([])

  const loading = ref(true)
  const loadError = ref<string | null>(null)

  /** What customers and the employee game list see; archived games are left out. */
  const catalogGames = computed(() => games.filter(g => !g.archived))

  /** Deleted games that were kept for their booking history, most recently deleted first. */
  const archivedGames = computed(() => games
    .filter(g => g.archived)
    .sort((a, b) => +(b.archivedAt ?? 0) - +(a.archivedAt ?? 0)))

  // ---------- loading ----------

  async function loadAll() {
    loading.value = true
    loadError.value = null
    try {
      const [gameRes, copyRes, linkRes, categoryRes, stepRes, userRes, bookingRes] = await Promise.all([
        supabase.from('board_game').select('*').order('game_name'),
        supabase.from('game_copy').select('*').order('copy_code'),
        supabase.from('game_category').select('game_id, category_id'),
        supabase.from('category').select('*').order('category_name'),
        supabase.from('how_to_play_step').select('*').order('game_id').order('step_number'),
        supabase.from('users').select('*'),
        supabase.from('booking').select('*').order('start_time')
      ])

      // how_to_play_step only exists once migrate_presentation.sql has run. Until then the
      // catalog still loads, just with no how-to-play steps and the default icon.
      const stepError = isMissingTable(stepRes.error) ? null : stepRes.error
      const firstError = gameRes.error || copyRes.error || linkRes.error || categoryRes.error || stepError || userRes.error || bookingRes.error
      if (firstError) throw firstError

      categories.splice(0, categories.length, ...(categoryRes.data ?? []).map(row => ({
        id: row.category_id,
        name: row.category_name
      })))
      const categoryById = new Map(categories.map(c => [c.id, c]))

      const categoriesByGame = new Map<string, Category[]>()
      for (const row of linkRes.data ?? []) {
        const cat = categoryById.get(row.category_id)
        if (!cat) continue
        const list = categoriesByGame.get(row.game_id) ?? []
        list.push(cat)
        categoriesByGame.set(row.game_id, list)
      }

      const stepsByGame = new Map<string, string[]>()
      for (const row of stepRes.error ? [] : stepRes.data ?? []) {
        const list = stepsByGame.get(row.game_id) ?? []
        list.push(row.step_text)
        stepsByGame.set(row.game_id, list)
      }

      const copiesByGame = new Map<string, Copy[]>()
      const copyToGame = new Map<string, string>()
      for (const row of copyRes.data ?? []) {
        const list = copiesByGame.get(row.game_id) ?? []
        list.push({
          id: row.copy_id,
          label: row.copy_code,
          number: row.copy_number,
          condition: row.condition_status as CopyCondition
        })
        copiesByGame.set(row.game_id, list)
        copyToGame.set(row.copy_id, row.game_id)
      }

      games.splice(0, games.length, ...(gameRes.data ?? []).map(row => ({
        id: row.game_id,
        name: row.game_name,
        description: row.description ?? '',
        icon: row.icon || DEFAULT_ICON,
        image: row.image_url || undefined,
        categories: (categoriesByGame.get(row.game_id) ?? []).sort((a, b) => a.name.localeCompare(b.name)),
        minP: row.min_players,
        maxP: row.max_players,
        playtime: row.play_time_mins,
        copies: copiesByGame.get(row.game_id) ?? [],
        howToPlay: stepsByGame.get(row.game_id) ?? [],
        // Undefined until migrate_archive.sql has run, which reads as "not archived".
        archived: !!row.deleted_at,
        archivedAt: row.deleted_at ? fromDbTimestamp(row.deleted_at) : null
      })))

      users.splice(0, users.length, ...(userRes.data ?? []).map(row => ({
        id: row.user_id,
        firstName: row.first_name,
        lastName: row.last_name,
        email: row.email,
        phone: row.phone ?? ''
      })))

      bookings.splice(0, bookings.length, ...(bookingRes.data ?? []).map(row => ({
        id: row.booking_id,
        gameId: copyToGame.get(row.copy_id) ?? '',
        copyId: row.copy_id,
        userId: row.user_id,
        start: fromDbTimestamp(row.start_time),
        end: fromDbTimestamp(row.end_time),
        status: row.status as BookingStatus,
        actualReturn: row.actual_return_time ? fromDbTimestamp(row.actual_return_time) : null,
        bookerName: row.booker_name ?? '',
        bookerPhone: row.booker_phone ?? ''
      })))

      await recomputeOverdue()
    } catch (e: unknown) {
      console.error('[store] loadAll failed', e)
      loadError.value = 'โหลดข้อมูลจากฐานข้อมูลไม่สำเร็จ กรุณาตรวจสอบการเชื่อมต่อแล้วรีเฟรชหน้าเว็บ'
    } finally {
      loading.value = false
    }
  }

  // ---------- id generation (schema uses VARCHAR primary keys, not sequences) ----------

  /**
   * Next `${prefix}NNN` id. Ids are compared as numbers, not text: sorting text puts
   * 'GM-WEREWOLF' above 'GM-007' and 'BK-999' above 'BK-1000', which would hand out
   * an id that is already taken. Ids whose tail isn't a number are ignored.
   */
  async function nextId(table: string, column: string, prefix: string, pad: number) {
    const { data, error } = await supabase.from(table).select(column).like(column, `${prefix}%`)
    if (error) throw error

    let max = 0
    for (const row of (data ?? []) as unknown as Record<string, string>[]) {
      const tail = String(row[column] ?? '').slice(prefix.length)
      if (/^\d+$/.test(tail)) max = Math.max(max, Number(tail))
    }
    return prefix + String(max + 1).padStart(pad, '0')
  }

  // ---------- reads over loaded state ----------

  function getUser(userId: string) {
    return users.find(u => u.id === userId)
  }

  function userLabel(userId: string) {
    const u = getUser(userId)
    return u ? `${u.firstName} ${u.lastName}` : '—'
  }

  function getGame(gameId: string) {
    return games.find(g => g.id === gameId)
  }

  /** The human box code (e.g. RICH-01) for a copy_id, which stays internal to the DB. */
  function copyLabel(copyId: string) {
    for (const g of games) {
      const copy = g.copies.find(c => c.id === copyId)
      if (copy) return copy.label
    }
    return copyId
  }

  function usableCopies(game: Game) {
    return game.copies.filter(isUsableCopy)
  }

  function copyStatus(copy: Copy): 'free' | 'busy' {
    const blocking = bookings.some(b => b.copyId === copy.id && (b.status === 'In_Use' || b.status === 'Overdue'))
    return blocking ? 'busy' : 'free'
  }

  function freeCopyCount(game: Game) {
    return usableCopies(game).filter(c => copyStatus(c) === 'free').length
  }

  function bookingsForCopy(copyId: string) {
    return bookings
      .filter(b => b.copyId === copyId && b.status !== 'Returned' && b.status !== 'Cancelled')
      .sort((a, b) => +a.start - +b.start)
  }

  /** Any booking at all, finished or not — what blocks deleting a box. */
  function copyHasHistory(copyId: string) {
    return bookings.some(b => b.copyId === copyId)
  }

  function gameHasHistory(gameId: string) {
    return getGame(gameId)?.copies.some(c => copyHasHistory(c.id)) ?? false
  }

  /** Bookings on this game still Reserved, In_Use or Overdue — what blocks deleting it. */
  function activeBookingCountForGame(gameId: string) {
    return getGame(gameId)?.copies.reduce((n, c) => n + activeBookingCount(c.id), 0) ?? 0
  }

  /** Games customers can still see in this category. */
  function categoryGameCount(categoryId: string) {
    return catalogGames.value.filter(g => g.categories.some(c => c.id === categoryId)).length
  }

  function activeBookingCount(copyId: string) {
    return bookings.filter(b => b.copyId === copyId && (b.status === 'Reserved' || b.status === 'In_Use' || b.status === 'Overdue')).length
  }

  function activeBookingsForUser(userId: string) {
    return bookings.filter(b => b.userId === userId && (b.status === 'Reserved' || b.status === 'In_Use'))
  }

  function hasOverdue(userId: string) {
    return bookings.some(b => b.userId === userId && b.status === 'Overdue')
  }

  function todayAt(h: number, m: number) {
    const d = new Date(simNow.value)
    d.setHours(h, m, 0, 0)
    return d
  }

  // ---------- validation done in the app (the DB covers BR-02/BR-03 itself) ----------

  function validateInput({ firstName, lastName, email, phone, start, end }: BookingInput): string | null {
    if (!firstName.trim() || !lastName.trim()) return 'กรุณากรอกชื่อและนามสกุล'
    if (!email.trim()) return 'กรุณากรอกอีเมล'
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) return 'รูปแบบอีเมลไม่ถูกต้อง'
    const digits = normalizePhone(phone)
    if (digits && (digits.length < 9 || digits.length > 10)) return 'เบอร์โทรต้องมี 9-10 หลัก'
    if (isNaN(+start) || isNaN(+end)) return 'กรุณาระบุช่วงเวลาให้ถูกต้อง'
    // No backdating: a slot that has already started can't be booked.
    if (start < simNow.value) return 'จองย้อนหลังไม่ได้ กรุณาเลือกเวลาที่ยังมาไม่ถึง'
    if (end <= start) return 'เวลาสิ้นสุดต้องอยู่หลังเวลาเริ่ม'
    const mins = (end.getTime() - start.getTime()) / 60000
    if (mins < 30) return 'ระยะเวลาการจองต้องอย่างน้อย 30 นาที (BR-02)'
    if (mins > 240) return 'ระยะเวลาการจองต้องไม่เกิน 4 ชั่วโมง (BR-02)'

    // A fast path only: `users` is readable by employees, so a customer's own
    // session sees an empty list and falls through. trg_enforce_booking_rules
    // applies BR-01 and BR-04 in the database either way.
    const existing = users.find(u => u.email === normalizeEmail(email))
    if (existing) {
      if (hasOverdue(existing.id)) return 'คุณมีรายการค้างสถานะ Overdue โปรดคืนเกมก่อนจองใหม่ (BR-04)'
      if (activeBookingsForUser(existing.id).length >= 2) return 'คุณมีรายการจองที่ใช้งาน/รอใช้งานอยู่แล้ว 2 รายการ (BR-01)'
    }
    return null
  }

  // ---------- booking writes ----------

  /**
   * Email is the identity: booking again with the same address reuses the users row.
   * `wasCreated` lets the caller undo the insert if the booking itself is rejected,
   * so a failed attempt doesn't leave an orphan user behind.
   */
  async function findOrCreateUser(input: BookingInput): Promise<{ id: string, wasCreated: boolean }> {
    // Customers can't read or insert public.users — it holds other people's names,
    // emails and phone numbers. This SECURITY DEFINER function does the lookup for
    // them and hands back only their own id. See supabase/migrate_users_privacy.sql.
    const { data, error } = await supabase.rpc('find_or_create_user', {
      p_email: normalizeEmail(input.email),
      p_first: input.firstName.trim(),
      p_last: input.lastName.trim(),
      p_phone: normalizePhone(input.phone) || null
    })
    if (error) throw error

    const row = (Array.isArray(data) ? data[0] : data) as
      { out_user_id: string, out_was_created: boolean } | undefined
    if (!row?.out_user_id) throw new Error('บันทึกข้อมูลผู้จองไม่สำเร็จ กรุณาลองใหม่อีกครั้ง')

    return { id: row.out_user_id, wasCreated: row.out_was_created }
  }

  async function addBooking(input: BookingInput): Promise<{ error: string | null }> {
    const invalid = validateInput(input)
    if (invalid) return { error: invalid }

    try {
      const user = await findOrCreateUser(input)

      const { error } = await supabase.from('booking').insert({
        booking_id: await nextId('booking', 'booking_id', 'BK-', 3),
        start_time: toDbTimestamp(input.start),
        end_time: toDbTimestamp(input.end),
        status: 'Reserved',
        user_id: user.id,
        copy_id: input.copyId
      })

      if (error) {
        // Roll back the user we just created, so a rejected booking leaves no trace.
        if (user.wasCreated) await supabase.from('users').delete().eq('user_id', user.id)
        return { error: messageForDbError(error) }
      }

      await loadAll()
      return { error: null }
    } catch (e: unknown) {
      return { error: messageForDbError(e as DbError) }
    }
  }

  /**
   * RLS lets only a signed-in employee update bookings. A blocked update comes back
   * with no error and zero rows, so success is judged by the rows returned.
   */
  async function markInUse(id: string, employeeId: string): Promise<BookingUpdate> {
    const { data, error } = await supabase
      .from('booking')
      .update({ status: 'In_Use', checkout_by_id: employeeId })
      .eq('booking_id', id)
      .select('booking_id')
    // A real refusal (a constraint, say) arrives as an error; RLS instead returns
    // zero rows and no error, so the two cases need different messages.
    if (error) return { booking: null, error: messageForDbError(error) }
    if (!data?.length) return { booking: null, error: NO_BOOKING_PERMISSION }
    const local = bookings.find(b => b.id === id)
    if (local) local.status = 'In_Use'
    return { booking: local ?? null, error: null }
  }

  async function markReturned(id: string, employeeId: string): Promise<BookingUpdate> {
    const now = new Date()
    const { data, error } = await supabase
      .from('booking')
      .update({ status: 'Returned', actual_return_time: toDbTimestamp(now), return_by_id: employeeId })
      .eq('booking_id', id)
      .select('booking_id')
    if (error) return { booking: null, error: messageForDbError(error) }
    if (!data?.length) return { booking: null, error: NO_BOOKING_PERMISSION }
    const local = bookings.find(b => b.id === id)
    if (local) {
      local.status = 'Returned'
      local.actualReturn = now
    }
    return { booking: local ?? null, error: null }
  }

  /**
   * The F-04 status sweep, run whenever the clock advances:
   *   Reserved, more than NO_SHOW_GRACE_MINUTES past start -> Cancelled (never collected)
   *   In_Use, past end_time                                -> Overdue
   *
   * Cancelling a no-show matters beyond tidiness: 'Cancelled' is outside the
   * exc_booking_no_overlap predicate, so the slot and the box are freed for
   * someone else, and the customer gets their BR-01 quota back.
   *
   * Always applied on screen; only persisted when an employee is signed in, since
   * customers' sessions aren't allowed to write bookings. supabase/migrate_noshow.sql
   * runs the same two rules in the database so they hold with nobody online.
   */
  async function recomputeOverdue() {
    const graceMs = NO_SHOW_GRACE_MINUTES * 60_000
    const noShows = bookings.filter(b => b.status === 'Reserved' && +simNow.value > +b.start + graceMs)
    const stale = bookings.filter(b => b.status === 'In_Use' && simNow.value > b.end)
    if (!noShows.length && !stale.length) return

    noShows.forEach(b => { b.status = 'Cancelled' })
    stale.forEach(b => { b.status = 'Overdue' })

    await Promise.all([
      noShows.length
        ? supabase.from('booking').update({ status: 'Cancelled' }).in('booking_id', noShows.map(b => b.id))
        : null,
      stale.length
        ? supabase.from('booking').update({ status: 'Overdue' }).in('booking_id', stale.map(b => b.id))
        : null
    ])
  }

  // ---------- catalog writes (employees only; enforced by RLS) ----------

  function cleanSteps(steps: string[]) {
    return steps.map(s => s.trim()).filter(Boolean)
  }

  function validateGameInput(input: GameInput): string | null {
    const name = input.name.trim()
    if (!name) return 'กรุณากรอกชื่อเกม'
    if (name.length > 150) return 'ชื่อเกมยาวได้ไม่เกิน 150 ตัวอักษร'
    // Postgres VARCHAR counts code points, which is what [...str] gives; .length counts UTF-16 units.
    if ([...input.icon.trim()].length > 16) return 'ไอคอนยาวได้ไม่เกิน 16 ตัวอักษร (ใส่อีโมจิ 1 ตัว)'
    if (!Number.isInteger(input.minP) || input.minP < 1) return 'จำนวนผู้เล่นขั้นต่ำต้องเป็นจำนวนเต็มตั้งแต่ 1 ขึ้นไป'
    if (!Number.isInteger(input.maxP) || input.maxP < input.minP) return 'จำนวนผู้เล่นสูงสุดต้องไม่น้อยกว่าขั้นต่ำ'
    if (!Number.isInteger(input.playtime) || input.playtime < 1) return 'เวลาเล่นต้องเป็นจำนวนเต็มนาทีตั้งแต่ 1 ขึ้นไป'
    return null
  }

  function toGameRow(input: GameInput) {
    return {
      game_name: input.name.trim(),
      description: input.description.trim() || null,
      icon: input.icon.trim() || DEFAULT_ICON,
      min_players: input.minP,
      max_players: input.maxP,
      play_time_mins: input.playtime
    }
  }

  /** Replaces the game's rows in game_category, which the ERD allows many of. */
  async function setGameCategories(gameId: string, categoryIds: string[]) {
    const { error: deleteError } = await supabase.from('game_category').delete().eq('game_id', gameId)
    if (deleteError) throw deleteError
    const unique = [...new Set(categoryIds)]
    if (!unique.length) return
    const { error } = await supabase
      .from('game_category')
      .insert(unique.map(categoryId => ({ game_id: gameId, category_id: categoryId })))
    if (error) throw error
  }

  /** Replaces the game's how_to_play_step rows, numbered 1..n in the given order. */
  async function setHowToPlay(gameId: string, steps: string[]) {
    const { error: deleteError } = await supabase.from('how_to_play_step').delete().eq('game_id', gameId)
    if (deleteError) throw deleteError
    const clean = cleanSteps(steps)
    if (!clean.length) return
    const { error } = await supabase
      .from('how_to_play_step')
      .insert(clean.map((text, i) => ({ game_id: gameId, step_number: i + 1, step_text: text })))
    if (error) throw error
  }

  /**
   * Box codes continue the game's existing pattern (WW-01, WW-02 → WW-03) and fall
   * back to the game id. copy_id is VARCHAR(20), so its prefix is trimmed to fit.
   */
  async function insertCopies(gameId: string, existing: Copy[], count: number): Promise<string | null> {
    const fromExisting = existing[0]?.label.replace(/-\d+$/, '')
    const prefix = (fromExisting || gameId.replace(/^GM-/, '')).toUpperCase()

    let n = existing.reduce((max, c) => Math.max(max, c.number), 0)
    const rows = Array.from({ length: count }, () => {
      n += 1
      const nn = String(n).padStart(2, '0')
      return {
        copy_id: `CP-${prefix.slice(0, 16 - nn.length)}-${nn}`,
        copy_code: `${prefix}-${nn}`,
        condition_status: 'Good',
        copy_number: n,
        game_id: gameId
      }
    })

    const { data, error } = await supabase.from('game_copy').insert(rows).select('copy_id')
    if (error) return messageForCatalogError(error)
    if ((data?.length ?? 0) !== count) return NO_CATALOG_PERMISSION
    return null
  }

  async function createGame(input: GameInput, copyCount: number): Promise<{ error: string | null, id: string | null }> {
    const invalid = validateGameInput(input)
    if (invalid) return { error: invalid, id: null }
    if (!Number.isInteger(copyCount) || copyCount < 0 || copyCount > MAX_COPIES_PER_ADD) {
      return { error: `จำนวนกล่องเริ่มต้นต้องอยู่ระหว่าง 0-${MAX_COPIES_PER_ADD}`, id: null }
    }

    let id: string
    try {
      id = await nextId('board_game', 'game_id', 'GM-', 3)
      const { error } = await supabase.from('board_game').insert({ game_id: id, ...toGameRow(input) })
      if (error) return { error: messageForCatalogError(error), id: null }
    } catch (e: unknown) {
      return { error: messageForCatalogError(e as DbError), id: null }
    }

    // The game row exists from here on, so any later failure still returns its id
    // and the caller can open the game to finish setting it up.
    let followUpError: string | null = null
    try {
      await setGameCategories(id, input.categoryIds)
      await setHowToPlay(id, input.howToPlay)
      if (copyCount > 0) followUpError = await insertCopies(id, [], copyCount)
    } catch (e: unknown) {
      followUpError = messageForCatalogError(e as DbError)
    }

    await loadAll()
    return { error: followUpError, id }
  }

  async function updateGame(gameId: string, input: GameInput): Promise<{ error: string | null }> {
    const invalid = validateGameInput(input)
    if (invalid) return { error: invalid }

    try {
      const { data, error } = await supabase
        .from('board_game').update(toGameRow(input)).eq('game_id', gameId).select('game_id')
      if (error) return { error: messageForCatalogError(error) }
      if (!data?.length) return { error: NO_CATALOG_PERMISSION }

      await setGameCategories(gameId, input.categoryIds)
      await setHowToPlay(gameId, input.howToPlay)
      await loadAll()
      return { error: null }
    } catch (e: unknown) {
      await loadAll()
      return { error: messageForCatalogError(e as DbError) }
    }
  }

  /**
   * Removes a game from the catalog. Refused while any of its bookings is still
   * Reserved, In_Use or Overdue.
   *
   * A game that was never booked is deleted for real, and its category links and
   * how-to-play steps go with it via ON DELETE CASCADE. A game with past bookings is
   * archived instead (board_game.deleted_at): booking.copy_id and game_copy.game_id are
   * ON DELETE RESTRICT, and deleting those rows would erase the booking history.
   */
  async function deleteGame(gameId: string): Promise<{ error: string | null, archived: boolean }> {
    if (!getGame(gameId)) return { error: 'ไม่พบเกมนี้', archived: false }
    const active = activeBookingCountForGame(gameId)
    if (active > 0) return { error: gameHasActiveBookingsMessage(active), archived: false }

    try {
      if (!gameHasHistory(gameId)) {
        // Delete by game_id so a box added from another device isn't missed. If a booking
        // appeared meanwhile, the database rejects the whole statement and removes
        // nothing — fall through and archive instead.
        const { error: copyError } = await supabase.from('game_copy').delete().eq('game_id', gameId)
        if (copyError && !isReferenced(copyError)) {
          return { error: messageForCatalogError(copyError), archived: false }
        }
        if (!copyError) {
          const { data, error } = await supabase.from('board_game').delete().eq('game_id', gameId).select('game_id')
          if (error) return { error: messageForCatalogError(error), archived: false }
          if (!data?.length) return { error: NO_CATALOG_PERMISSION, archived: false }
          await loadAll()
          return { error: null, archived: false }
        }
      }

      const { data, error } = await supabase
        .from('board_game')
        .update({ deleted_at: toDbTimestamp(new Date()) })
        .eq('game_id', gameId)
        .select('game_id')
      if (error) return { error: messageForCatalogError(error), archived: false }
      if (!data?.length) return { error: NO_CATALOG_PERMISSION, archived: false }

      await loadAll()
      return { error: null, archived: true }
    } catch (e: unknown) {
      await loadAll()
      return { error: messageForCatalogError(e as DbError), archived: false }
    }
  }

  /** Puts an archived game back in the catalog, with its boxes and history as they were. */
  async function restoreGame(gameId: string): Promise<{ error: string | null }> {
    const { data, error } = await supabase
      .from('board_game').update({ deleted_at: null }).eq('game_id', gameId).select('game_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  function validateCategoryName(clean: string, exceptId?: string): string | null {
    if (!clean) return 'กรุณากรอกชื่อหมวดหมู่'
    if (clean.length > 100) return 'ชื่อหมวดหมู่ยาวได้ไม่เกิน 100 ตัวอักษร'
    // category_name is UNIQUE but case-sensitive in the DB; also catch "party" vs "Party".
    if (categories.some(c => c.id !== exceptId && c.name.toLowerCase() === clean.toLowerCase())) {
      return 'มีหมวดหมู่ชื่อนี้อยู่แล้ว'
    }
    return null
  }

  async function renameCategory(categoryId: string, name: string): Promise<{ error: string | null }> {
    const current = categories.find(c => c.id === categoryId)
    if (!current) return { error: 'ไม่พบหมวดหมู่นี้' }
    const clean = name.trim()
    if (clean === current.name) return { error: null }
    const invalid = validateCategoryName(clean, categoryId)
    if (invalid) return { error: invalid }

    const { data, error } = await supabase
      .from('category').update({ category_name: clean }).eq('category_id', categoryId).select('category_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  async function createCategory(name: string): Promise<{ error: string | null }> {
    const clean = name.trim()
    const invalid = validateCategoryName(clean)
    if (invalid) return { error: invalid }

    try {
      const { data, error } = await supabase
        .from('category')
        .insert({ category_id: await nextId('category', 'category_id', 'CAT-', 3), category_name: clean })
        .select('category_id')
      if (error) return { error: messageForCatalogError(error) }
      if (!data?.length) return { error: NO_CATALOG_PERMISSION }
      await loadAll()
      return { error: null }
    } catch (e: unknown) {
      return { error: messageForCatalogError(e as DbError) }
    }
  }

  /** Adds one game_category row, leaving the game's other categories as they are. */
  async function addGameToCategory(gameId: string, categoryId: string): Promise<{ error: string | null }> {
    const { data, error } = await supabase
      .from('game_category').insert({ game_id: gameId, category_id: categoryId }).select('game_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  /** Removes one game_category row; the game itself is untouched. */
  async function removeGameFromCategory(gameId: string, categoryId: string): Promise<{ error: string | null }> {
    const { data, error } = await supabase
      .from('game_category').delete().eq('game_id', gameId).eq('category_id', categoryId).select('game_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  /** Games are kept; only their link to this category goes (game_category is ON DELETE CASCADE). */
  async function deleteCategory(categoryId: string): Promise<{ error: string | null }> {
    const { data, error } = await supabase.from('category').delete().eq('category_id', categoryId).select('category_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  async function addCopies(gameId: string, count: number): Promise<{ error: string | null }> {
    if (!Number.isInteger(count) || count < 1 || count > MAX_COPIES_PER_ADD) {
      return { error: `เพิ่มได้ครั้งละ 1-${MAX_COPIES_PER_ADD} กล่อง` }
    }
    const game = getGame(gameId)
    if (!game) return { error: 'ไม่พบเกมนี้' }

    const error = await insertCopies(gameId, game.copies, count)
    if (error) return { error }
    await loadAll()
    return { error: null }
  }

  async function setCopyCondition(copyId: string, condition: CopyCondition): Promise<{ error: string | null }> {
    const { data, error } = await supabase
      .from('game_copy').update({ condition_status: condition }).eq('copy_id', copyId).select('copy_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  async function deleteCopy(copyId: string): Promise<{ error: string | null }> {
    if (copyHasHistory(copyId)) return { error: COPY_HAS_HISTORY }

    const { data, error } = await supabase.from('game_copy').delete().eq('copy_id', copyId).select('copy_id')
    if (error) return { error: messageForCatalogError(error) }
    if (!data?.length) return { error: NO_CATALOG_PERMISSION }
    await loadAll()
    return { error: null }
  }

  // ---------- clock ----------

  /** The clock always follows the device's real time — it can't be overridden. */
  function syncToRealTime() {
    simNow.value = new Date()
    void recomputeOverdue()
  }

  void loadAll()

  return {
    games,
    catalogGames,
    categories,
    users,
    bookings,
    loading,
    loadError,
    loadAll,
    getUser,
    userLabel,
    simNow,
    todayAt,
    copyStatus,
    getGame,
    copyLabel,
    usableCopies,
    freeCopyCount,
    bookingsForCopy,
    copyHasHistory,
    gameHasHistory,
    activeBookingCount,
    addBooking,
    markInUse,
    markReturned,
    createGame,
    updateGame,
    deleteGame,
    activeBookingCountForGame,
    createCategory,
    renameCategory,
    addGameToCategory,
    removeGameFromCategory,
    deleteCategory,
    archivedGames,
    restoreGame,
    categoryGameCount,
    addCopies,
    setCopyCondition,
    deleteCopy,
    syncToRealTime,
    recomputeOverdue
  }
}

export function useBoardGameStore() {
  if (!store) store = createStore(useSupabaseClient())
  return store
}
