import { reactive, ref } from 'vue'
import type { SupabaseClient } from '@supabase/supabase-js'
import { FALLBACK_PRESENTATION, gamePresentation } from '~/composables/gamePresentation'

// Matches the status CHECK constraint on public.booking in supabase/schema.sql
export type BookingStatus = 'Reserved' | 'In_Use' | 'Overdue' | 'Returned' | 'Cancelled'

export interface Copy {
  id: string
  label: string
}

export interface Game {
  id: string
  name: string
  description: string
  icon: string
  image?: string
  category: string
  minP: number
  maxP: number
  playtime: number
  copies: Copy[]
  howToPlay: string[]
}

/** Mirrors public.users. user_id is generated by the system — nobody types it. */
export interface User {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
}

export interface Booking {
  id: string
  gameId: string
  copyId: string
  userId: string
  start: Date
  end: Date
  status: BookingStatus
  actualReturn: Date | null
}

export interface BookingInput {
  firstName: string
  lastName: string
  email: string
  phone: string
  gameId: string
  copyId: string
  start: Date
  end: Date
}

function normalizeEmail(email: string) {
  return email.trim().toLowerCase()
}

function normalizePhone(phone: string) {
  return phone.replace(/[^0-9]/g, '')
}

/**
 * public.booking stores TIMESTAMP (no time zone), so send local wall-clock text.
 * Sending a Date directly would serialise to UTC and shift every booking by the
 * device's offset (-7h in Thailand).
 */
function toDbTimestamp(d: Date) {
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`
}

/** '2026-09-08T14:00:00' has no offset, so JS parses it as local time — the inverse of the above. */
function fromDbTimestamp(value: string) {
  return new Date(value)
}

/** Turns a Postgres constraint violation into the message a booker should see. */
function messageForDbError(err: { code?: string, message?: string } | null): string {
  if (!err) return 'บันทึกข้อมูลไม่สำเร็จ'
  const detail = `${err.code ?? ''} ${err.message ?? ''}`
  if (err.code === '23P01' || detail.includes('exc_booking_no_overlap')) {
    return 'ช่วงเวลานี้ถูกจองไปแล้ว กรุณาเลือกเวลาอื่น (BR-03)'
  }
  if (detail.includes('chk_booking_duration')) {
    return 'ระยะเวลาการจองต้องอยู่ระหว่าง 30 นาที ถึง 4 ชั่วโมง (BR-02)'
  }
  if (detail.includes('chk_booking_return_time')) {
    return 'เวลาคืนต้องไม่ก่อนเวลาเริ่มใช้งาน'
  }
  if (err.code === '23505' && detail.includes('email')) {
    return 'อีเมลนี้ถูกใช้กับชื่ออื่นแล้ว กรุณาตรวจสอบอีกครั้ง'
  }
  return `บันทึกข้อมูลไม่สำเร็จ: ${err.message ?? 'ไม่ทราบสาเหตุ'}`
}

let store: ReturnType<typeof createStore> | null = null

function createStore(supabase: SupabaseClient) {
  const simNow = ref(new Date())
  const isTimeOverridden = ref(false)

  const games = reactive<Game[]>([])
  const users = reactive<User[]>([])
  const bookings = reactive<Booking[]>([])

  const loading = ref(true)
  const loadError = ref<string | null>(null)

  // ---------- loading ----------

  async function loadAll() {
    loading.value = true
    loadError.value = null
    try {
      const [gameRes, copyRes, catRes, userRes, bookingRes] = await Promise.all([
        supabase.from('board_game').select('*').order('game_name'),
        supabase.from('game_copy').select('*').order('copy_code'),
        supabase.from('game_category').select('game_id, category:category_id (category_id, category_name)'),
        supabase.from('users').select('*'),
        supabase.from('booking').select('*').order('start_time')
      ])

      const firstError = gameRes.error || copyRes.error || catRes.error || userRes.error || bookingRes.error
      if (firstError) throw firstError

      const categoryByGame = new Map<string, string>()
      for (const row of catRes.data ?? []) {
        const cat = row.category as { category_name?: string } | null
        if (cat?.category_name && !categoryByGame.has(row.game_id)) {
          categoryByGame.set(row.game_id, cat.category_name)
        }
      }

      const copiesByGame = new Map<string, Copy[]>()
      for (const row of copyRes.data ?? []) {
        const list = copiesByGame.get(row.game_id) ?? []
        list.push({ id: row.copy_id, label: row.copy_code })
        copiesByGame.set(row.game_id, list)
      }

      const copyToGame = new Map<string, string>()
      for (const row of copyRes.data ?? []) copyToGame.set(row.copy_id, row.game_id)

      games.splice(0, games.length, ...(gameRes.data ?? []).map(row => {
        const look = gamePresentation[row.game_id] ?? FALLBACK_PRESENTATION
        return {
          id: row.game_id,
          name: row.game_name,
          description: row.description ?? '',
          icon: look.icon,
          image: look.image,
          category: categoryByGame.get(row.game_id) ?? 'อื่นๆ',
          minP: row.min_players,
          maxP: row.max_players,
          playtime: row.play_time_mins,
          copies: copiesByGame.get(row.game_id) ?? [],
          howToPlay: look.howToPlay
        }
      }))

      users.splice(0, users.length, ...(userRes.data ?? []).map(row => ({
        id: row.user_id,
        firstName: row.first_name,
        lastName: row.last_name,
        email: row.email,
        phone: row.phone ?? ''
      })))

      bookings.splice(0, bookings.length, ...(bookingRes.data ?? []).map(row => ({
        id: row.booking_id,
        gameId: copyToGame.get(row.copy_id) ?? '',
        copyId: row.copy_id,
        userId: row.user_id,
        start: fromDbTimestamp(row.start_time),
        end: fromDbTimestamp(row.end_time),
        status: row.status as BookingStatus,
        actualReturn: row.actual_return_time ? fromDbTimestamp(row.actual_return_time) : null
      })))

      await recomputeOverdue()
    } catch (e: unknown) {
      const err = e as { message?: string }
      loadError.value = err.message ?? 'โหลดข้อมูลจากฐานข้อมูลไม่สำเร็จ'
    } finally {
      loading.value = false
    }
  }

  // ---------- id generation (schema uses VARCHAR primary keys, not sequences) ----------

  async function nextId(table: string, column: string, prefix: string, pad: number) {
    const { data } = await supabase
      .from(table)
      .select(column)
      .like(column, `${prefix}%`)
      .order(column, { ascending: false })
      .limit(1)

    const latest = (data?.[0] as Record<string, string> | undefined)?.[column]
    const n = latest ? Number(latest.slice(prefix.length)) : 0
    return prefix + String((Number.isFinite(n) ? n : 0) + 1).padStart(pad, '0')
  }

  // ---------- reads over loaded state ----------

  function getUser(userId: string) {
    return users.find(u => u.id === userId)
  }

  function userLabel(userId: string) {
    const u = getUser(userId)
    return u ? `${u.firstName} ${u.lastName}` : '—'
  }

  function getGame(gameId: string) {
    return games.find(g => g.id === gameId)
  }

  function copyStatus(copy: Copy): 'free' | 'busy' {
    const blocking = bookings.some(b => b.copyId === copy.id && (b.status === 'In_Use' || b.status === 'Overdue'))
    return blocking ? 'busy' : 'free'
  }

  function freeCopyCount(game: Game) {
    return game.copies.filter(c => copyStatus(c) === 'free').length
  }

  function bookingsForCopy(copyId: string) {
    return bookings
      .filter(b => b.copyId === copyId && b.status !== 'Returned' && b.status !== 'Cancelled')
      .sort((a, b) => +a.start - +b.start)
  }

  function activeBookingsForUser(userId: string) {
    return bookings.filter(b => b.userId === userId && (b.status === 'Reserved' || b.status === 'In_Use'))
  }

  function hasOverdue(userId: string) {
    return bookings.some(b => b.userId === userId && b.status === 'Overdue')
  }

  function todayAt(h: number, m: number) {
    const d = new Date(simNow.value)
    d.setHours(h, m, 0, 0)
    return d
  }

  // ---------- validation done in the app (the DB covers BR-02/BR-03 itself) ----------

  function validateInput({ firstName, lastName, email, phone, start, end }: BookingInput): string | null {
    if (!firstName.trim() || !lastName.trim()) return 'กรุณากรอกชื่อและนามสกุล'
    if (!email.trim()) return 'กรุณากรอกอีเมล'
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) return 'รูปแบบอีเมลไม่ถูกต้อง'
    const digits = normalizePhone(phone)
    if (digits && (digits.length < 9 || digits.length > 10)) return 'เบอร์โทรต้องมี 9-10 หลัก'
    if (isNaN(+start) || isNaN(+end)) return 'กรุณาระบุช่วงเวลาให้ถูกต้อง'
    if (end <= start) return 'เวลาสิ้นสุดต้องอยู่หลังเวลาเริ่ม'
    const mins = (end.getTime() - start.getTime()) / 60000
    if (mins < 30) return 'ระยะเวลาการจองต้องอย่างน้อย 30 นาที (BR-02)'
    if (mins > 240) return 'ระยะเวลาการจองต้องไม่เกิน 4 ชั่วโมง (BR-02)'

    // BR-01/BR-04 are per person; an unseen email is a new user with no history.
    const existing = users.find(u => u.email === normalizeEmail(email))
    if (existing) {
      if (hasOverdue(existing.id)) return 'คุณมีรายการค้างสถานะ Overdue โปรดคืนเกมก่อนจองใหม่ (BR-04)'
      if (activeBookingsForUser(existing.id).length >= 2) return 'คุณมีรายการจองที่ใช้งาน/รอใช้งานอยู่แล้ว 2 รายการ (BR-01)'
    }
    return null
  }

  // ---------- writes ----------

  /**
   * Email is the identity: booking again with the same address reuses the users row.
   * `wasCreated` lets the caller undo the insert if the booking itself is rejected,
   * so a failed attempt doesn't leave an orphan user behind.
   */
  async function findOrCreateUser(input: BookingInput): Promise<{ id: string, wasCreated: boolean }> {
    const email = normalizeEmail(input.email)

    const { data: found, error: findError } = await supabase
      .from('users').select('user_id').eq('email', email).maybeSingle()
    if (findError) throw findError
    if (found) return { id: found.user_id, wasCreated: false }

    const { data: created, error: insertError } = await supabase
      .from('users')
      .insert({
        user_id: await nextId('users', 'user_id', 'U', 3),
        first_name: input.firstName.trim(),
        last_name: input.lastName.trim(),
        email,
        phone: normalizePhone(input.phone) || null
      })
      .select('user_id')
      .single()
    if (insertError) throw insertError

    return { id: created.user_id, wasCreated: true }
  }

  async function addBooking(input: BookingInput): Promise<{ error: string | null }> {
    const invalid = validateInput(input)
    if (invalid) return { error: invalid }

    try {
      const user = await findOrCreateUser(input)

      const { error } = await supabase.from('booking').insert({
        booking_id: await nextId('booking', 'booking_id', 'BK-', 3),
        start_time: toDbTimestamp(input.start),
        end_time: toDbTimestamp(input.end),
        status: 'Reserved',
        user_id: user.id,
        copy_id: input.copyId
      })

      if (error) {
        // Roll back the user we just created, so a rejected booking leaves no trace.
        if (user.wasCreated) await supabase.from('users').delete().eq('user_id', user.id)
        return { error: messageForDbError(error) }
      }

      await loadAll()
      return { error: null }
    } catch (e: unknown) {
      return { error: messageForDbError(e as { code?: string, message?: string }) }
    }
  }

  async function markInUse(id: string) {
    const { error } = await supabase.from('booking').update({ status: 'In_Use' }).eq('booking_id', id)
    if (error) return null
    const local = bookings.find(b => b.id === id)
    if (local) local.status = 'In_Use'
    return local
  }

  async function markReturned(id: string) {
    const now = new Date()
    const { error } = await supabase
      .from('booking')
      .update({ status: 'Returned', actual_return_time: toDbTimestamp(now) })
      .eq('booking_id', id)
    if (error) return null
    const local = bookings.find(b => b.id === id)
    if (local) {
      local.status = 'Returned'
      local.actualReturn = now
    }
    return local
  }

  /** The F-04 overdue scan: flip In_Use bookings whose end_time has passed. */
  async function recomputeOverdue() {
    const stale = bookings.filter(b => b.status === 'In_Use' && simNow.value > b.end)
    if (!stale.length) return
    const ids = stale.map(b => b.id)
    const { error } = await supabase.from('booking').update({ status: 'Overdue' }).in('booking_id', ids)
    if (!error) stale.forEach(b => { b.status = 'Overdue' })
  }

  // ---------- clock ----------

  function syncToRealTime() {
    if (isTimeOverridden.value) return
    simNow.value = new Date()
    void recomputeOverdue()
  }

  function setSimNow(d: Date) {
    isTimeOverridden.value = true
    simNow.value = d
    void recomputeOverdue()
  }

  function resetToRealTime() {
    isTimeOverridden.value = false
    simNow.value = new Date()
    void recomputeOverdue()
  }

  void loadAll()

  return {
    games,
    users,
    bookings,
    loading,
    loadError,
    loadAll,
    getUser,
    userLabel,
    simNow,
    isTimeOverridden,
    todayAt,
    copyStatus,
    getGame,
    freeCopyCount,
    bookingsForCopy,
    addBooking,
    markInUse,
    markReturned,
    setSimNow,
    syncToRealTime,
    resetToRealTime,
    recomputeOverdue
  }
}

export function useBoardGameStore() {
  if (!store) store = createStore(useSupabaseClient())
  return store
}
